### ISSUE TITLE
BUG: function_ is not a function

### ISSUE THREAD

**Issue by adminy** [sindresorhus/p-queue#212]
I like this lib. Just the default examples seem to be broken.

```
// queye.add(() => asyncFn()) // works
// queue.add(asyncFN()) // errors with:

| TypeError: function_ is not a function
     at file:///root/proj/node_modules/p-queue/dist/index.js:180:37
     at #tryToStartAnother (file:///root/proj/node_modules/p-queue/dist/index.js:118:17)
     at file:///root/proj/node_modules/p-queue/dist/index.js:204:36
     at new Promise (<anonymous>)
     at PQueue.add (file:///root/proj/node_modules/p-queue/dist/index.js:174:16)

**Comment by adminy** [comment]
seems that its not expecting a promise thats already in progress, which makes sense
